Добавил новые механики игры
leaderdsn/team-09-app pull request #15
Opened 2022-11-23 15:13 UTC by Gerfey

2022-11-23 16:00 UTC, practicum-maxim-zyryanov requested changes
Вероятно можно улучшить архитектуру решения, да и время сейчас есть, поэтому прошу посмотреть по замечаниям.

2022-11-23 16:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/game/render.ts
> +    foods.forEach(renderFood.bind(null, me));
Необходимость передавать `me` даже для отрисовку фона начинает вызывать вопросы, фактически `me` требуется для получения координат. Странно смотрится теперь и `renderPlayer(me, me)`. Возможно стоит обособить координаты внутри `Entity`:
```
type Entity = {
  id: string;
  coordinates: {
     x: number;
     y: number;
  }
  ...
}
```

Получим немного более ясный код:
```
    let viewCoordinates = me.coordinates;
    renderBackground(viewCoordinates)
    renderBorder(viewCoordinates)
    renderPlayer(viewCoordinates, me)
```

2022-11-23 16:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/game/render.ts
> +  if (!canvas || !context) return
Строка много где дублируется, возможно назревает время создать иерархию классов `Entity` с методом `render`, который и скроет общий технический код.
```
class Entity {
   public render(canvasCoordinates) {
      if (!canvas || !context) return;
      draw(canvasCoordinates)
   }

   public draw(canvasCoordinates) {
      // отрисовка
   }
}
```

2022-11-23 16:00 UTC, practicum-maxim-zyryanov commented on packages/server/src/entity/player.js
> +    this.mass += dt * touchEntity.mass * 25 / 35;
Если со значением 100 мог предполагать, что вычисляется процент, то 35 ставит меня в тупик - рекомендую ввести константу с осмысленным названием.

2022-11-23 16:00 UTC, practicum-maxim-zyryanov commented on packages/server/src/entity/sourness.js
> +}
Код очень похож на то, что уже видел в классе `Food`, создаётся ощущение, что не полностью использованы все преимущества наследования.

2022-11-23 16:00 UTC, practicum-maxim-zyryanov commented on packages/server/src/game/game.js
> +    }
Слишком большая функция и много дублирования

2022-11-23 16:00 UTC, practicum-maxim-zyryanov commented on packages/server/src/game/game.js
> +      // })
Если комментарий и решаешь оставить, советую отписать прямо в коде причину. Например: "Удалить, если не возникнет проблем с методом таким-то" или "Предварительное решение, удалить при слиянии ветки такой-то"

2022-11-23 16:00 UTC, practicum-maxim-zyryanov commented on packages/server/src/game/game.js
> +          }
Если условных конструкций становится больше и появляются `instanceof`, то всегда следует заподозрить неправильную архитектуру. На фоне того, что писал выше, вероятно действительно можно архитектурно улучшить приложение.

2022-11-23 16:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/game/assets.ts
> +      // @ts-ignore
Сейчас понимаю отчего множатся `@ts-ignore`, но рекомендую постепенно избавляться от них, изменяя код. Уже сейчас игнорирование множится как вирус, это чревато ошибками в дальнейшем.

2022-12-02 08:48 UTC, leaderdsn commented on packages/client/src/game/render.ts
>    mass: number,
не используешь prettier, где-то "," а где то ";"

2022-12-02 09:33 UTC, leaderdsn commented on packages/client/src/game/render.ts
>    color: string | CanvasGradient | CanvasPattern,
если возможно это будет где-то ещё использоваться string | CanvasGradient | CanvasPattern то лучше наверное вынести в отдельный тип

2022-12-02 11:33 UTC, leaderdsn commented on packages/client/src/game/render.ts
> +function renderPlayer(current: Entity | null, player: Entity) {
в src/types есть type Nullable<T> можно использовать его

2022-12-02 11:46 UTC, leaderdsn approved these changes
Хорошая, работа! Указал несколько небольших замечаний, мне только показалось что ты не  пользуешься prettier, потому что почти во всех файлах не хватает ";"

2022-12-05 11:23 UTC, practicum-maxim-zyryanov requested changes
К основной логике вопросов нет, но есть ряд небольших замечаний к местам, которые могут вызывать проблемы при чтении кода другими или при дальнейшей поддержке.

2022-12-05 11:23 UTC, practicum-maxim-zyryanov commented on packages/server/index.js
> +httpServer.listen(8080);
Т.к. порт может меняться чаще, чем код, то также рекомендовал бы вынести его в настройку, чтобы избежать изменения файла и перекомпиляции для конфигурации.

2022-12-05 11:23 UTC, practicum-maxim-zyryanov commented on packages/server/src/Core/Core.js
> +      this.deltaTime = Math.abs(this.lastUpdateTime - now) / this.frameTime
Можно опустить повторные вычисления:
```this.deltaTime = deltaTime```

2022-12-05 11:23 UTC, practicum-maxim-zyryanov commented on packages/server/src/Entity/Variation/Food.js
> +    this.mass = new MassEntity(0.25, 2, 0.0005, Math.floor(Math.random() * (2 - 0.25 + 1) + 0.25))
Здесь происходит магия: не сразу ясно, что означают значения, приходится обращаться к определению. Чтобы улучшить наглядность можно ввести дополнительные переменные. Также вынес бы вычисление значения в отдельную функцию, т.к. похоже оно зависит от min и max.
```
let min = 0.25
let max = 2
let factor = 0.0005
let value = calculateFoodValue(min, max)
this.mass = new MassEntity(min, max, factor, value)
```

2022-12-05 11:23 UTC, practicum-maxim-zyryanov commented on packages/server/src/Entity/Variation/Player.js
> +    this.score = new ScoreEntity(0.25, 0.25, 0)
Вновь набор значений и не ясно какие на самом деле одни и те же, а какие по стечению обстоятельств равны, поэтому когда возникнет необходимость 0.25 поменять на 0.75 потребуется много времени определить, а правильно ли все значения менять на новое. Если ввести переменные, то взаимосвязь станет нагляднее (далее код условный, лишь для демонстрации, что так видна взаимосвязь)
```
let a = 25;
let b = 10;
let c = 5;
let d = 100;
let z = 0;
let f = 0.0005;
let e = 0.2;
let k = 13;
let m = 0.5;
let h = 0.25;
let w = 0.25;

this.radius = new RadiusEntity(a, b)
this.mass = new MassEntity(e, k, f, m)
this.speed = new SpeedEntity(c * b, c * b + d, z)
this.score = new ScoreEntity(h, w, z)
```

Кроме того, некоторые значения ранее встречал, и вероятно стоит создать под них отдельный конфиг игры, где будут заданы настройки для еды, игроков и т.д. Иначе также сложно будет определить в каких местах требуется ещё изменить значения, если исправил например значение фактора в игроке.

2022-12-05 11:23 UTC, practicum-maxim-zyryanov commented on packages/server/src/Generator/SocketMessageGenerator.js
> +      otherPlayer => otherPlayer.type === 'player' && otherPlayer !== player && otherPlayer.distanceTo(player) <= 500
500 - тоже значение, которое вынести бы в конфиг

2022-12-13 07:07 UTC, Gerfey commented on packages/server/src/Entity/Variation/Player.js
> +    this.score = new ScoreEntity(0.25, 0.25, 0)
не соглашусь, что передается в конструктор видно через любую IDE, плодить кучу переменных ради сомнительной читабельности. признак плохого(грязного) кода, считаю что делать так не стоит.

2022-12-26 13:22 UTC, merged